In [1]:
import pandas as pd

In [2]:
import glob

In [10]:
fp = 'C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB/*.csv'

In [12]:
name_lst = []
for name in glob.glob(fp):
        position = name.index('.csv')
        name = name[0:position]
        name_lst.append(name)
name_lst

['C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek - 2020_07_14, 19 16 25 - CB walking indoor LED power grey S',
 'C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek - 2020_07_14, 19 26 32 - CB housework indoor LED vented grey M',
 'C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek - 2020_07_14, 19 31 19 - CB sitting indoor LED power clear S',
 'C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek - 2020_07_14, 19 36 49 - CB housework indoor LED power clear S',
 'C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek - 2020_07_14, 19 40 26 - CB walking indoor LED power clear S',
 'C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek - 2020_07_14, 19 45 49 - CB sitting indoor LED vented clear M',
 'C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek - 2020_07_14, 19 49 48 - CB housework indoor LED vented clear M']

In [35]:
df1 = pd.read_csv(glob.glob(fp)[0])
df2 = pd.read_csv(glob.glob(fp)[1])
pd.concat([df1,df2])

,Seg,Timestamp,ENOS-154,HR,RRi,RSpeed,RCadence,RDist,QoS,OoE,...,RSpeed.1,RCadence.1,RDist.1,QoS.1,OoE.1,FOM1.1,FOM2.1,FOM3.1,StepCount.1,AM.1
0,1,2020-07-14 19:16:26.534,NaN,70,NaN,0.000000,0,400,72,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020-07-14 19:16:27.534,NaN,71,NaN,0.000000,0,400,70,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2020-07-14 19:16:28.534,NaN,72,NaN,0.000000,0,400,67,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2020-07-14 19:16:29.534,NaN,73,NaN,0.000000,0,400,57,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2020-07-14 19:16:30.534,NaN,74,NaN,0.000000,71,400,56,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,1,2020-07-14 19:29:28.863,NaN,95,NaN,0.988281,106,136,56,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,1,2020-07-14 19:29:29.863,NaN,94,NaN,1.054688,104,137,54,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,1,2020-07-14 19:29:30.863,NaN,94,NaN,1.050781,104,138,54,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,1,2020-07-14 19:29:31.863,NaN,94,NaN,1.050781,100,139,54,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,1,2020-07-14 19:29:32.862,NaN,94,NaN,0.984375,89,140,48,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
fname = name_lst[0].split("-")[2]

In [31]:
nl=glob.glob(fp)

In [32]:
nl[0].split("-")

['C:/Users/57lzhang/Desktop/Internal Data During Office Shutdown/Dome Eval_Ambulatory/CB\\PTek ',
 ' 2020_07_14, 19 16 25 ',
 ' CB walking indoor LED power grey S.csv']

In [34]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [ ]:
#def a function to read each file and create columns to store the filename information
def read_file(fp):
    overall_df = pd.DataFrame()
    
    for i in glob.glbo(fp):
        fname = i.split("-")[2]
        subject = fname.split(" ")[1]
        activity = fname.split(" ")[2]
        dome_type = fname.split(" ")[5]
        dome_color = fname.split(" ")[6]

        df = pd.read_csv(i)
        #select timestamp and HR from polar and bioric to make a new dataframe
        new_df 
        df['Subject'] = subject
        df['Activity'] = activity
        df['Dome_Type'] = dome_type
        df['Dome_Color'] = dome_color
        
        overall_df = pd.concat([overall_df, df])